---
name: Task - Benchmark

on:
  workflow_dispatch:
  workflow_call:

jobs:
  benchmark:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - uses: actions/cache@v3
        with:
          path: |
            ~/.cargo/bin/
            ~/.cargo/registry/index/
            ~/.cargo/registry/cache/
            ~/.cargo/git/db/
            target/
          key:
            ${{ runner.os }}-cargo-${{ hashFiles('Cargo.lock') }}-${{
            github.run_id }}
          fail-on-cache-miss: true
      - name: Setup Madara
        run: target/release/madara setup --chain=dev --from-remote
      - name: Run Madara in background
        id: madara
        run: |
          target/release/madara --dev &
          echo "RUN_PID=$\!" >> "$GITHUB_OUTPUT"
          while ! echo exit | nc localhost 9944; do sleep 1; done
      - name: Run Gomu Gomu no Gatling Action
        uses: keep-starknet-strange/gomu-gomu-no-gatling/.github/actions@main
        with:
          config_path: "benchmark.yml"
      - name: Stop Madara
        run: kill "${{ steps.madara.outputs.RUN_PID }}"
