---
name: Workflow - Pull Request

on:
  workflow_dispatch:
  pull_request:
    branches: [main]

jobs:
  changelog:
    name: Enforce CHANGELOG
    uses: ./.github/workflows/changelog.yml

  configs-verifier:
    name: Verify configs
    uses: ./.github/workflows/configs-verifier.yml

  linters:
    name: Run linters
    uses: ./.github/workflows/linters.yml
    needs: [changelog, configs-verifier]

  rust_build:
    name: Build Rust project
    uses: ./.github/workflows/rust-build.yml
    needs: [changelog, configs-verifier]

  madara_commands:
    name: Test Madara commands
    uses: ./.github/workflows/madara-commands.yml
    needs: rust_build

  linters_cargo:
    name: Run Cargo linters
    uses: ./.github/workflows/linters-cargo.yml
    needs: rust_build

  tests:
    name: Run tests
    uses: ./.github/workflows/tests.yml
    needs: rust_build

  rpc-tests:
    name: Run rpc tests
    uses: ./.github/workflows/starknet-rpc-tests.yml
    needs: rust_build

  benchmark:
    name: Run benchmarks
    uses: ./.github/workflows/benchmarks.yml
    needs: rust_build
