---
name: Workflow - Push

on:
  workflow_dispatch:
  push:
    branches: [main]

jobs:
  linters:
    name: Run linters
    uses: ./.github/workflows/linters.yml

  rust_build_test:
    name: Build & Integration Tests
    uses: ./.github/workflows/rust-build-test.yml

  madara_commands:
    name: Test Madara commands
    uses: ./.github/workflows/madara-commands.yml
    needs: [linters, rust_build_test]

  linters_cargo:
    name: Run Cargo linters
    uses: ./.github/workflows/linters-cargo.yml
    needs: madara_commands

  rpc-tests:
    name: Run rpc tests
    uses: ./.github/workflows/starknet-rpc-tests.yml
    needs: madara_commands

  benchmark:
    name: Run benchmarks
    uses: ./.github/workflows/benchmarks.yml
    needs: madara_commands

  rustdoc:
    name: Deploy docs to GitHub Pages
    uses: ./.github/workflows/rustdoc.yml
    needs: benchmark
    permissions:
      contents: write
